package uniandes.sischok.mundo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import uniandes.sischok.mundo.Incidente;

import uniandes.sischok.mundo.IncidenteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig incidenteDaoConfig;

    private final IncidenteDao incidenteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        incidenteDaoConfig = daoConfigMap.get(IncidenteDao.class).clone();
        incidenteDaoConfig.initIdentityScope(type);

        incidenteDao = new IncidenteDao(incidenteDaoConfig, this);

        registerDao(Incidente.class, incidenteDao);
    }
    
    public void clear() {
        incidenteDaoConfig.getIdentityScope().clear();
    }

    public IncidenteDao getIncidenteDao() {
        return incidenteDao;
    }

}
