package uniandes.sischok.mundo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INCIDENTE.
 */
public class Incidente {

	//--------Atributos---------
	
	
	/**
	 *  Llave primaria
	 */
    private Long id;
	
	/**
	 * Titulo el incidente. Valor no Nulo
	 */
    private String titulo;

	/**
	 * Descripcion del incidente
	 */
    private String descripcion;
	/**
	 * Zona donde ocurrio el incidente. Zonas delimitadas por mapa de bogota.
	 */
    private Integer zona;
    
	/**
	 * Gravedad del incidente. Base del 1 al 5.
	 */
    private Integer gravedad;
    
	/**
	 * Fecha de Creación del incidente
	 */
    private java.util.Date fechaCreacion;
	
	/**
	 * Usuario que creo el incidente
	 */
    private String usuarioCreacion;

    public Incidente() {
    }

    public Incidente(Long id) {
        this.id = id;
    }

    public Incidente(Long id, String titulo, String descripcion, Integer zona, Integer gravedad, java.util.Date fechaCreacion, String usuarioCreacion) {
        this.id = id;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.zona = zona;
        this.gravedad = gravedad;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitulo() {
        return titulo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getZona() {
        return zona;
    }

    public void setZona(Integer zona) {
        this.zona = zona;
    }

    public Integer getGravedad() {
        return gravedad;
    }

    public void setGravedad(Integer gravedad) {
        this.gravedad = gravedad;
    }

    public java.util.Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(java.util.Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

}
