package uniandes.sischok.mundo;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;

import org.json.JSONObject;
import org.json.JSONException;
// KEEP INCLUDES END
/**
 * Entity mapped to table INCIDENTE.
 */
public class Incidente {

    private Long id;
    private String idServidor;
    /** Not-null value. */
    private String titulo;
    private String descripcion;
    private Integer zona;
    private Integer gravedad;
    private Long latitud;
    private Long longitud;
    private java.util.Date fechaCreacion;
    private String usuarioCreacion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Incidente() {
    }

    public Incidente(Long id) {
        this.id = id;
    }

    public Incidente(Long id, String idServidor, String titulo, String descripcion, Integer zona, Integer gravedad, Long latitud, Long longitud, java.util.Date fechaCreacion, String usuarioCreacion) {
        this.id = id;
        this.idServidor = idServidor;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.zona = zona;
        this.gravedad = gravedad;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdServidor() {
        return idServidor;
    }

    public void setIdServidor(String idServidor) {
        this.idServidor = idServidor;
    }

    /** Not-null value. */
    public String getTitulo() {
        return titulo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getZona() {
        return zona;
    }

    public void setZona(Integer zona) {
        this.zona = zona;
    }

    public Integer getGravedad() {
        return gravedad;
    }

    public void setGravedad(Integer gravedad) {
        this.gravedad = gravedad;
    }

    public Long getLatitud() {
        return latitud;
    }

    public void setLatitud(Long latitud) {
        this.latitud = latitud;
    }

    public Long getLongitud() {
        return longitud;
    }

    public void setLongitud(Long longitud) {
        this.longitud = longitud;
    }

    public java.util.Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(java.util.Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    // KEEP METHODS - put your custom methods here
    
    @Override
    public String toString() {
    	JSONObject jobjIncA = new JSONObject();
    			try {
    				jobjIncA.put("titulo", titulo);
    				jobjIncA.put("gravedad",gravedad);
    				jobjIncA.put("zona", zona);
    				jobjIncA.put("descripcion", descripcion);
    				jobjIncA.put("latitud",latitud);
    				jobjIncA.put("longitud", longitud);
    				jobjIncA.put("fechaCreacion", fechaCreacion.toString());
    				jobjIncA.put("usuarioCreacion", usuarioCreacion);
    			} catch (JSONException e) {
    				e.printStackTrace();
    			}
    	return jobjIncA.toString();
    }
    
    public static Incidente toIncidente (JSONObject jsonO)
    {
    	Incidente objInc= null;
    	try {
    		objInc = new Incidente( Long.valueOf(jsonO.getLong("id")), jsonO.getString("idServidor"),jsonO.getString("titulo"), jsonO.getString("descripcion"),  Integer.valueOf(jsonO.getInt("zona")),  Integer.valueOf(jsonO.getInt("gravedad")),  Long.valueOf(jsonO.getLong("latitud")),  Long.valueOf(jsonO.getLong("longitud")), (Date)jsonO.get("fechaCreacion"), jsonO.getString("usuarioCreacion"));
		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	return objInc;
    }
    
    // KEEP METHODS END

}
